FROM node:alpine

RUN mkdir -p /app

ENV PORT 3000

EXPOSE 3000

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . /app

RUN npx next telemetry disable

CMD [ "npm", "run", "dev" ]
